name: suggest_a_feature_firestore
description: A package that contains the firestore based data source for suggest_a_feature.
version: 0.0.3
repository: https://github.com/What-the-Flutter/Suggest-a-Feature-Firestore

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  cloud_firestore: ^4.5.0
  flutter:
    sdk: flutter
  suggest_a_feature: ^0.0.3

dev_dependencies:
  fake_cloud_firestore: ^2.4.1+1
  lints: ^2.0.1
  test: ^1.22.0
  very_good_analysis: ^4.0.0+1